export const eventPreLoad = [
  {
    id: 1,
    name: "Evento1",
    description: "Descripción del evento",
    image: "https://picsum.photos/200/300",
    date: "16 de Junio",
    stock: 1000,
    price: 1000,
    localization: "General",
  },
  {
    id: 2,
    name: "Evento2",
    description: "Descripción del evento",
    image: "https://picsum.photos/200/300",
    date: "16 de Junio",
    stock: 1000,
    price: 1000,
    localization: "General",
  },
  {
    id: 3,
    name: "Evento3",
    description: "Descripción del evento",
    image: "https://picsum.photos/200/300",
    date: "16 de Junio",
    stock: 1000,
    price: 1000,
    localization: "General",
  },
  {
    id: 4,
    name: "Evento4",
    description: "Descripción del evento",
    image: "https://picsum.photos/200/300",
    date: "16 de Junio",
    stock: 1000,
    price: 1000,
    localization: "General",
  },
  {
    id: 5,
    name: "Evento5",
    description: "Descripción del evento",
    image: "https://picsum.photos/200/300",
    date: "16 de Junio",
    stock: 1000,
    price: 1000,
    localization: "General",
  },
  {
    id: 6,
    name: "Evento6",
    description: "Descripción del evento",
    image: "https://picsum.photos/200/300",
    date: "16 de Junio",
    stock: 1000,
    price: 1000,
    localization: "General",
  },
  {
    id: 7,
    name: "Evento7",
    description: "Descripción del evento",
    image: "https://picsum.photos/200/300",
    date: "16 de Junio",
    stock: 1000,
    price: 1000,
    localization: "General",
  },
  {
    id: 8,
    name: "Evento8",
    description: "Descripción del evento",
    image: "https://picsum.photos/200/300",
    date: "16 de Junio",
    stock: 1000,
    price: 1000,
    localization: "General",
  },
  {
    id: 9,
    name: "Evento9",
    description: "Descripción del evento",
    image: "https://picsum.photos/200/300",
    date: "16 de Junio",
    stock: 1000,
    price: 1000,
    localization: "General",
  },
  {
    id: 10,
    name: "Evento10",
    description: "Descripción del evento",
    image: "https://picsum.photos/200/300",
    date: "16 de Junio",
    stock: 1000,
    price: 1000,
    localization: "General",
  },
  {
    id: 11,
    name: "Evento11",
    description: "Descripción del evento",
    image: "https://picsum.photos/200/300",
    date: "16 de Junio",
    stock: 1000,
    price: 1000,
    localization: "General",
  },
  {
    id: 12,
    name: "Evento12",
    description: "Descripción del evento",
    image: "https://picsum.photos/200/300",
    date: "16 de Junio",
    stock: 1000,
    price: 1000,
    localization: "General",
  },
  {
    id: 13,
    name: "Evento13",
    description: "Descripción del evento",
    image: "https://picsum.photos/200/300",
    date: "16 de Junio",
    stock: 1000,
    price: 1000,
    localization: "General",
  },
  {
    id: 14,
    name: "Evento14",
    description: "Descripción del evento",
    image: "https://picsum.photos/200/300",
    date: "16 de Junio",
    stock: 1000,
    price: 1000,
    localization: "General",
  },
  {
    id: 15,
    name: "Evento15",
    description: "Descripción del evento",
    image: "https://picsum.photos/200/300",
    date: "16 de Junio",
    stock: 1000,
    price: 1000,
    localization: "General",
  },
  {
    id: 16,
    name: "Evento16",
    description: "Descripción del evento",
    image: "https://picsum.photos/200/300",
    date: "16 de Junio",
    stock: 1000,
    price: 1000,
    localization: "General",
  },
  {
    id: 17,
    name: "Evento17",
    description: "Descripción del evento",
    image: "https://picsum.photos/200/300",
    date: "16 de Junio",
    stock: 1000,
    price: 1000,
    localization: "General",
  },
  {
    id: 18,
    name: "Evento18",
    description: "Descripción del evento",
    image: "https://picsum.photos/200/300",
    date: "16 de Junio",
    stock: 1000,
    price: 1000,
    localization: "General",
  },
  {
    id: 19,
    name: "Evento19",
    description: "Descripción del evento",
    image: "https://picsum.photos/200/300",
    date: "16 de Junio",
    stock: 1000,
    price: 1000,
    localization: "General",
  },
  {
    id: 20,
    name: "Evento20",
    description: "Descripción del evento",
    image: "https://picsum.photos/200/300",
    date: "16 de Junio",
    stock: 1000,
    price: 1000,
    localization: "General",
  },
];
