import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MyFooter from "@/components/Footer/MyFooter";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <MyFooter/>
        </body>
    </html>
  );
}
